force-app/main/default/objects/Record_Alert_Display_Config__mdt/Record_Alert_Display_Config__mdt.object-meta.xml
<CustomObject>
    <description>Configurations for the Record Alert Display Lightning Web Component.</description>
    <label>Record Alert Display Config</label>
    <pluralLabel>Record Alert Display Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Record_Alert_Display_Config__mdt/fields/Record_Alert_Category_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Alert_Category_Developer_Name__c</fullName>
    <label>Record Alert Category Developer Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Record_Alert_Display_Config__mdt/fields/Record_Alert_Icon__c.field-meta.xml
<CustomField>
    <fullName>Record_Alert_Icon__c</fullName>
    <inlineHelpText>Developer name of the static resource or an SLDS icon name to associate with that record alert category. If no value is set the the default icon will load.</inlineHelpText>
    <label>Record Alert Icon</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RecordAlertCardIconController.cls
public without sharing class RecordAlertCardIconController {

    @AuraEnabled(cacheable=true)
    public static String getStaticResourceUrl(String recordAlertCategoryId) {
        // Retrieve the RecordAlertCategory DeveloperName based on the ID
        RecordAlertCategory category;
        try{
            category = [SELECT DeveloperName FROM RecordAlertCategory WHERE Id = :recordAlertCategoryId LIMIT 1];
        } catch (QueryException e) {
            throw new AuraHandledException('Record Alert is not assigned a Record Alert Category');
        }

        Record_Alert_Display_Config__mdt displayConfig;
        try{
            displayConfig = [SELECT Record_Alert_Icon__c FROM Record_Alert_Display_Config__mdt WHERE Record_Alert_Category_Developer_Name__c = :category.DeveloperName LIMIT 1];
        } catch (QueryException e){
            throw new AuraHandledException('No Record_Alert_Display_Config__mdt created for Record Alert Category: ' + category.DeveloperName);
        }

        // Retrieve the StaticResource record with ContentType
        List<StaticResource> staticResources = [SELECT Id, Name, ContentType FROM StaticResource WHERE Name = :displayConfig.Record_Alert_Icon__c LIMIT 1];
        String icon;

        if (!staticResources.isEmpty()) {
            // Validate if the static resource has a valid image content type
            StaticResource staticResource = staticResources[0];
            String contentType = staticResource.ContentType;
            if (!contentType.startsWith('image/')) {
                throw new AuraHandledException('The static resource ' + staticResource.Name + ' is not an image.');
            }

            // Generate the URL for the static resource
            icon = '/resource/' + staticResource.Name;
        } else if(displayConfig.Record_Alert_Icon__c.contains(':')) {
            icon = displayConfig.Record_Alert_Icon__c;
        } else {
            throw new AuraHandledException('No static resource or icon found with the name: ' + displayConfig.Record_Alert_Icon__c);
        }

        return icon;
    }
}