force-app/main/default/objects/Record_Alert_Display_Config__mdt/Record_Alert_Display_Config__mdt.object-meta.xml
<CustomObject>
    <description>Configurations for the Record Alert Display Lightning Web Component.</description>
    <label>Record Alert Display Config</label>
    <pluralLabel>Record Alert Display Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Record_Alert_Display_Config__mdt/fields/Flow_Action_ApiName__c.field-meta.xml
<CustomField>
    <fullName>Flow_Action_ApiName__c</fullName>
    <label>Flow Action ApiName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Record_Alert_Display_Config__mdt/fields/Flow_Action_Button_Label__c.field-meta.xml
<CustomField>
    <fullName>Flow_Action_Button_Label__c</fullName>
    <description>Label for the button that will be associated with each Record Alert Category.</description>
    <inlineHelpText>Label for the button that will be associated with each Record Alert Category.</inlineHelpText>
    <label>Flow Action Button Label</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Record_Alert_Display_Config__mdt/fields/Record_Alert_Category_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Alert_Category_Developer_Name__c</fullName>
    <label>Record Alert Category Developer Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RecordAlertCardActionController.cls
public with sharing class RecordAlertCardActionController {
    @AuraEnabled(cacheable=true)
    public static String getCategoryActions(String recordAlertCategoryId) {
        RecordAlertCategory category;
        try{
            category = [SELECT DeveloperName FROM RecordAlertCategory WHERE Id = :recordAlertCategoryId LIMIT 1];
            
        } catch (QueryException e){
            throw new AuraHandledException('Record Alert is not assigned a Record Alert Category');
        }

        Record_Alert_Display_Config__mdt categoryFlowName;
        try{
            categoryFlowName = [SELECT Flow_Action_ApiName__c FROM Record_Alert_Display_Config__mdt WHERE Record_Alert_Category_Developer_Name__c = :category.DeveloperName LIMIT 1];
        } catch (QueryException e){
            throw new AuraHandledException('No Record_Alert_Display_Config__mdt created for this Record Alert Category');
        }

        FlowDefinitionView flowDefinition;
        try{
            flowDefinition = [SELECT Id, Label, ApiName FROM FlowDefinitionView WHERE ApiName = :categoryFlowName.Flow_Action_ApiName__c LIMIT 1];
        } catch (QueryException e) {
            throw new AuraHandledException('No Flow created for this Record Alert Category');
        }


        return flowDefinition.ApiName;
    }

    @AuraEnabled(cacheable=true)
    public static String getButtonLabel(String recordAlertCategoryId) {
        RecordAlertCategory category;
        try{
            category = [SELECT DeveloperName FROM RecordAlertCategory WHERE Id = :recordAlertCategoryId LIMIT 1];
            
        } catch (QueryException e){
            throw new AuraHandledException('Record Alert is not assigned a Record Alert Category');
        }

        Record_Alert_Display_Config__mdt categoryConfig;
        try{
            categoryConfig = [SELECT Flow_Action_Button_Label__c 
                            FROM Record_Alert_Display_Config__mdt 
                            WHERE Record_Alert_Category_Developer_Name__c = :category.DeveloperName LIMIT 1];
        } catch (QueryException e){
            throw new AuraHandledException('No Record_Alert_Display_Config__mdt created for this Record Alert Category');
        }

        return categoryConfig.Flow_Action_Button_Label__c;
    }
}