force-app/main/default/objects/Record_Alert_Display_Config__mdt/Record_Alert_Display_Config__mdt.object-meta.xml
<CustomObject>
    <description>Configurations for the Record Alert Display Lightning Web Component.</description>
    <label>Record Alert Display Config</label>
    <pluralLabel>Record Alert Display Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Record_Alert_Display_Config__mdt/fields/Record_Alert_Category_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Alert_Category_Developer_Name__c</fullName>
    <label>Record Alert Category Developer Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Record_Alert_Display_Config__mdt/fields/Record_Alert_Icon__c.field-meta.xml
<CustomField>
    <fullName>Record_Alert_Icon__c</fullName>
    <inlineHelpText>Developer name of the static resource or an SLDS icon name to associate with that record alert category. If no value is set the the default icon will load.</inlineHelpText>
    <label>Record Alert Icon</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RecordAlertCardIconControllerTest.cls
@IsTest
public with sharing class RecordAlertCardIconControllerTest {
    @IsTest
    static void testGetCategoryIcons_StaticResource_Success() {
        RecordAlertCategory testCategory = [SELECT Id, DeveloperName FROM RecordAlertCategory WHERE DeveloperName = 'RecordAlert_Behavior' LIMIT 1];
        System.System.debug(testCategory);
        Record_Alert_Display_Config__mdt testConfig = [SELECT Id,Record_Alert_Icon__c FROM Record_Alert_Display_Config__mdt WHERE Record_Alert_Category_Developer_Name__c = :testCategory.DeveloperName LIMIT 1];
        System.System.debug(testConfig);
        StaticResource testResource = [SELECT Id, Name, ContentType FROM StaticResource WHERE Name = :testConfig.Record_Alert_Icon__c LIMIT 1];
        System.System.debug(testResource);
        String testUrl = '/resource/' + testResource.Name;
        
        Test.startTest();
        String result = RecordAlertCardIconController.getStaticResourceUrl(testCategory.Id);
        Test.stopTest();

        // Assert the result
        System.assertEquals(testUrl, result, 'The returned API name should match the test flow');
    }
    
    @IsTest
    static void testGetCategoryIcons_SldsIcon_Success() {
        RecordAlertCategory testCategory = [SELECT Id, DeveloperName FROM RecordAlertCategory WHERE DeveloperName = 'RecordAlert_Academic' LIMIT 1];
        System.System.debug(testCategory);
        Record_Alert_Display_Config__mdt testConfig = [SELECT Id,Record_Alert_Icon__c FROM Record_Alert_Display_Config__mdt WHERE Record_Alert_Category_Developer_Name__c = :testCategory.DeveloperName LIMIT 1];
        System.System.debug(testConfig);
        String testUrl = testConfig.Record_Alert_Icon__c;
        
        Test.startTest();
        String result = RecordAlertCardIconController.getStaticResourceUrl(testCategory.Id);
        Test.stopTest();

        // Assert the result
        System.assertEquals(testUrl, result, 'The returned API name should match the test flow');
    }

    @IsTest
    static void testGetCategoryIcons_InvalidCategoryId() {
        Test.startTest();
        try {
            RecordAlertCardIconController.getStaticResourceUrl('InvalidId');
            System.assert(false, 'Expected an exception to be thrown');
        } catch (Exception e) { 
            System.assertEquals('Script-thrown exception', e.getMessage());
        } 
        Test.stopTest();
    }

    @IsTest
    static void testGetCategoryIcons_InvalidDisplayConfig() {
        RecordAlertCategory testCategory = [SELECT Id, DeveloperName FROM RecordAlertCategory WHERE DeveloperName = 'RecordAlert_Financial' LIMIT 1];

        Test.startTest();
        try {
            String result = RecordAlertCardIconController.getStaticResourceUrl(testCategory.Id);
            System.assert(false, 'Expected an exception to be thrown');
        } catch (Exception e) { 
            System.assertEquals('Script-thrown exception', e.getMessage());
        } 
        Test.stopTest();
    }

}